const liftAccessories = [
  {
    id: 1,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbdt-175ya.png",
    model: "WBDT - 175YA",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 2,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbdt-175yb.png",
    model: "WBDT - 175YB",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 3,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbdt-175yd.png",
    model: "WBDT - 175YB",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 4,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbjd-k-04.png",
    model: "WBJD-K-04",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 5,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbjd-k-05.png",
    model: "WBJD-K-05",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 6,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbjd-k-06.png",
    model: "WBJD-K-06",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 7,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbjd-k-07.png",
    model: "WBJD-K-07",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 8,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbjd-k-08.png",
    model: "WBJD-K-08",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 9,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbjd-k-09.png",
    model: "WBJD-K-09",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 10,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbjd-k-10.png",
    model: "WBJD-K-10",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 11,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbjd-k-11.png",
    model: "WBJD-K-11",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 12,
    category: "celling",
    product_img: "/assets/images/products/lifts/accessories/wbjd-k-12.png",
    model: "WBJD-K-12",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 13,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-01.png",
    model: "WBMB-S-01",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 14,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-02.png",
    model: "WBMB-S-02",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 15,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-03.png",
    model: "WBMB-S-03",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 16,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-04.png",
    model: "WBMB-S-04",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 17,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-05.png",
    model: "WBMB-S-05",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 18,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-06.png",
    model: "WBMB-S-06",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 19,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-07.png",
    model: "WBMB-S-07",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 20,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-08.png",
    model: "WBMB-S-08",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 21,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-09.png",
    model: "WBMB-S-09",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 22,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-10.png",
    model: "WBMB-S-10",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 23,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-11.png",
    model: "WBMB-S-11",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 24,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-12.png",
    model: "WBMB-S-12",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 25,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-13.png",
    model: "WBMB-S-13",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 26,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-14.png",
    model: "WBMB-S-14",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 27,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-15.png",
    model: "WBMB-S-15",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 28,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-16.png",
    model: "WBMB-S-16",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 29,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-17.png",
    model: "WBMB-S-17",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 30,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-18.png",
    model: "WBMB-S-18",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 31,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-19.png",
    model: "WBMB-S-19",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 32,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-20.png",
    model: "WBMB-S-20",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 33,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-21.png",
    model: "WBMB-S-21",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 34,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-22.png",
    model: "WBMB-S-22",
    details: "Stainless Steel plate, tube lamp",
  },
  {
    id: 35,
    category: "landing-door",
    product_img: "/assets/images/products/lifts/accessories/wbmb-s-23.png",
    model: "WBMB-S-23",
    details: "Stainless Steel plate, tube lamp",
  },
];

export default liftAccessories;
